from enum import Enum


class Languages(Enum):
    zh_cn = "ChineseSimplified"
    zh_tw = "ChineseTraditional"
    cs = "Czech"
    da = "Danish"
    nl = "Dutch"
    en = "English"
    et = "Estonian"
    fi = "Finnish"
    fr = "French"
    de = "German"
    hu = "Hungarian"
    it = "Italian"
    ja = "Japanese"
    ko = "Korean"
    no = "Norwegian"
    pl = "Polish"
    pt = "Portuguese"
    pt_br = "PortugueseBrazilian"
    ro = "Romanian"
    ru = "Russian"
    sk = "Slovak"
    es = "Spanish"
    es_la = "SpanishLatin"
    sv = "Swedish"
    tr = "Turkish"
    uk = "Ukrainian"
